import type { Module } from "../types";

// Starting fuel (matches initial fueltank capacity)
export const STARTING_FUEL = 80;

// Base ID for initial modules - ensures no collision with dynamically generated IDs
// Dynamic modules use Date.now() which is always > 1000
const INITIAL_MODULE_BASE_ID = 100;

// Initial ship modules
export const initialModules: Module[] = [
    {
        id: INITIAL_MODULE_BASE_ID + 1,
        type: "reactor",
        name: "Реактор",
        x: 1,
        y: 1,
        width: 1,
        height: 1,
        power: 10,
        health: 100,
        maxHealth: 100,
        level: 1,
        defense: 1,
    },
    {
        id: INITIAL_MODULE_BASE_ID + 2,
        type: "cockpit",
        name: "Кабина",
        x: 2,
        y: 1,
        width: 1,
        height: 1,
        consumption: 1,
        health: 100,
        maxHealth: 100,
        level: 1,
        defense: 1,
    },
    {
        id: INITIAL_MODULE_BASE_ID + 3,
        type: "lifesupport",
        name: "Жизнеобеспечение",
        x: 1,
        y: 2,
        width: 1,
        height: 1,
        consumption: 2,
        health: 100,
        maxHealth: 100,
        oxygen: 5,
        level: 1,
        defense: 1,
    },
    {
        id: INITIAL_MODULE_BASE_ID + 4,
        type: "cargo",
        name: "Грузовой отсек",
        x: 2,
        y: 2,
        width: 1,
        height: 1,
        consumption: 1,
        capacity: 40,
        health: 100,
        maxHealth: 100,
        level: 1,
        defense: 1,
    },
    {
        id: INITIAL_MODULE_BASE_ID + 5,
        type: "engine",
        name: "Двигатель",
        x: 3,
        y: 1,
        width: 1,
        height: 1,
        consumption: 1,
        health: 100,
        maxHealth: 100,
        level: 1,
        fuelEfficiency: 10,
        defense: 1,
    },
    {
        id: INITIAL_MODULE_BASE_ID + 6,
        type: "fueltank",
        name: "Топливный бак",
        x: 3,
        y: 2,
        width: 1,
        height: 1,
        health: 100,
        maxHealth: 100,
        level: 1,
        capacity: STARTING_FUEL,
        defense: 1,
    },
    // {
    //     id: INITIAL_MODULE_BASE_ID + 7,
    //     type: "lab",
    //     name: "Лаборатория",
    //     x: 1,
    //     y: 3,
    //     width: 1,
    //     height: 1,
    //     consumption: 2,
    //     health: 100,
    //     maxHealth: 100,
    //     level: 1,
    //     defense: 1,
    // },
    // {
    //     id: INITIAL_MODULE_BASE_ID + 8,
    //     type: "weaponbay",
    //     name: "Боевая палуба (debug)",
    //     x: 1,
    //     y: 4,
    //     width: 1,
    //     height: 1,
    //     consumption: 2,
    //     health: 100,
    //     maxHealth: 100,
    //     level: 1,
    //     defense: 1,
    //     weapons: [{ type: "quantum_torpedo" }],
    // },
    // {
    //     id: INITIAL_MODULE_BASE_ID + 8,
    //     type: "weaponbay",
    //     name: "Боевая палуба (debug)",
    //     x: 1,
    //     y: 4,
    //     width: 1,
    //     height: 1,
    //     consumption: 2,
    //     health: 100,
    //     maxHealth: 100,
    //     level: 1,
    //     defense: 1,
    //     weapons: [{ type: "quantum_torpedo" }],
    // },
    // {
    //     id: INITIAL_MODULE_BASE_ID + 9,
    //     type: "weaponbay",
    //     name: "Боевая палуба (debug)",
    //     x: 1,
    //     y: 5,
    //     width: 1,
    //     height: 1,
    //     consumption: 2,
    //     health: 100,
    //     maxHealth: 100,
    //     level: 1,
    //     defense: 1,
    //     weapons: [{ type: "quantum_torpedo" }],
    // },
];
