import type { Module } from "../types";

// Starting fuel (matches initial fueltank capacity)
export const STARTING_FUEL = 80;

// Initial ship modules
export const initialModules: Module[] = [
    {
        id: 1,
        type: "reactor",
        name: "Реактор",
        x: 1,
        y: 1,
        width: 1,
        height: 1,
        power: 10,
        health: 100,
        maxHealth: 100,
        level: 1,
        defense: 1,
    },
    {
        id: 2,
        type: "cockpit",
        name: "Кабина",
        x: 2,
        y: 1,
        width: 1,
        height: 1,
        consumption: 1,
        health: 100,
        maxHealth: 100,
        level: 1,
        defense: 1,
    },
    {
        id: 3,
        type: "lifesupport",
        name: "Жизнеобеспечение",
        x: 1,
        y: 2,
        width: 1,
        height: 1,
        consumption: 2,
        health: 100,
        maxHealth: 100,
        oxygen: 5,
        level: 1,
        defense: 1,
    },
    {
        id: 4,
        type: "cargo",
        name: "Грузовой отсек",
        x: 2,
        y: 2,
        width: 1,
        height: 1,
        consumption: 1,
        capacity: 40,
        health: 100,
        maxHealth: 100,
        level: 1,
        defense: 1,
    },
    {
        id: 5,
        type: "engine",
        name: "Двигатель",
        x: 3,
        y: 1,
        width: 1,
        height: 1,
        consumption: 1,
        health: 100,
        maxHealth: 100,
        level: 1,
        fuelEfficiency: 10,
        defense: 1,
    },
    {
        id: 6,
        type: "fueltank",
        name: "Топливный бак",
        x: 3,
        y: 2,
        width: 1,
        height: 1,
        health: 100,
        maxHealth: 100,
        level: 1,
        capacity: STARTING_FUEL,
        defense: 1,
    },
];
