export const EXPEDITION_GRID_SIZE = 5;
export const EXPEDITION_TILE_COUNT = 25;
export const EXPEDITION_MAX_ARTIFACTS = 2;

export const EXPEDITION_MARKET_CREDITS_MIN = 150;
export const EXPEDITION_MARKET_CREDITS_MAX = 400;

export const EXPEDITION_LAB_RESOURCE_MIN = 1;
export const EXPEDITION_LAB_RESOURCE_MAX = 3;

export const EXPEDITION_INCIDENT_DAMAGE_MIN = 20;
export const EXPEDITION_INCIDENT_DAMAGE_MAX = 35;
export const EXPEDITION_INCIDENT_MORALE_LOSS = 12;

export const EXPEDITION_GOOD_FIND_MORALE_BOOST = 4;

export const EXPEDITION_CREW_SCOUT_EXP = 20;
export const EXPEDITION_CREW_OTHER_EXP = 8;
