import type { PartialModuleType, ShopItem } from "../types";

export const MODULE_TYPES: Record<
    PartialModuleType,
    { color: string; borderColor: string }
> = {
    reactor: { color: "#ffb00033", borderColor: "#ffb000" },
    cockpit: { color: "#00d4ff33", borderColor: "#00d4ff" },
    lifesupport: { color: "#00ff4133", borderColor: "#00ff41" },
    cargo: { color: "#ff004033", borderColor: "#ff0040" },
    weaponbay: { color: "#ff00ff33", borderColor: "#ff00ff" },
    shield: { color: "#0080ff33", borderColor: "#0080ff" },
    medical: { color: "#00ffaa33", borderColor: "#00ffaa" },
    scanner: { color: "#ffff0033", borderColor: "#ffff00" },
    engine: { color: "#ff660033", borderColor: "#ff6600" },
    fueltank: { color: "#9933ff33", borderColor: "#9933ff" },
    drill: { color: "#8b451333", borderColor: "#cd853f" },
    ai_core: { color: "#00ffff33", borderColor: "#00ffff" },
    lab: { color: "#00ff4133", borderColor: "#00ff41" },
};

export const MODULES_BY_PRIOTITY = [
    { type: "cargo", name: "Грузовой отсек" },
    { type: "fueltank", name: "Топливный бак" },
    { type: "scanner", name: "Сканер" },
    { type: "drill", name: "Бур" },
    { type: "weaponbay", name: "Оружейная палуба" },
    { type: "shield", name: "Генератор щита" },
    { type: "engine", name: "Двигатель" },
] satisfies {
    type: PartialModuleType;
    name: string;
}[];

export const EMERGENCY_SHUTDOWN_DAMAGE = 0.1; // 10% урона модулю, когда он аварийно выключен из-за отсутствия энергии
export const DEFAULT_MAX_HEALTH_MODULE = 100;
export const MIN_MODULE_HEALTH = 0;
export const BASE_SHIELD_REGEN_MIN = 5;
export const BASE_SHIELD_REGEN_MAX = 10;

export const MODULES_FROM_BOSSES: ShopItem[] = [
    {
        id: "engine-quantum",
        name: "★ Двигатель Ур.4",
        type: "module",
        moduleType: "engine",
        level: 4,
        maxHealth: 200,
        width: 2,
        height: 2,
        power: 0,
        consumption: 0,
        fuelEfficiency: 10,
        price: 10000,
        stock: 1,
        description: "Квантовый двигатель без потребления топлива",
    },
    {
        id: "drill-ancient",
        name: "★ Древний бур",
        type: "module",
        moduleType: "drill",
        level: 4,
        maxHealth: 200,
        width: 1,
        height: 2,
        consumption: 2,
        price: 3000,
        stock: 1,
        description: "Технология древних для эффективной добычи",
    },
    {
        id: "reactor-fusion",
        name: "★ Термоядерный реактор",
        type: "module",
        moduleType: "reactor",
        level: 4,
        maxHealth: 200,
        width: 1,
        height: 1,
        power: 30,
        consumption: 0,
        price: 4000,
        stock: 1,
        description: "Реактор на холодном синтезе",
    },
    {
        id: "shield-ancient",
        name: "★ Древний щит",
        type: "module",
        moduleType: "shield",
        level: 4,
        maxHealth: 200,
        width: 2,
        height: 1,
        shields: 80,
        consumption: 5,
        price: 5000,
        stock: 1,
        description: "Непревзойдённая защита древних",
    },
    {
        id: "cargo-quantum",
        name: "★ Квантовый склад",
        type: "module",
        moduleType: "cargo",
        level: 4,
        maxHealth: 200,
        width: 2,
        height: 1,
        capacity: 250,
        consumption: 3,
        price: 3500,
        stock: 1,
        description: "Квантовое хранение грузов",
    },
    {
        id: "scanner-quantum",
        name: "★ Квантовый сканер",
        type: "module",
        moduleType: "scanner",
        level: 4,
        maxHealth: 200,
        width: 1,
        height: 1,
        scanRange: 15,
        consumption: 9,
        price: 3000,
        stock: 1,
        description: "Сканирование через квантовую запутанность",
    },
    {
        id: "fueltank-ancient",
        name: "★ Древний топливный бак",
        type: "module",
        moduleType: "fueltank",
        level: 4,
        maxHealth: 200,
        width: 1,
        height: 1,
        capacity: 260,
        price: 4000,
        stock: 1,
        description: "Ёмкость из сплава древних",
    },
    {
        id: "lifesupport-ancient",
        name: "★ Древнее жизнеобеспечение",
        type: "module",
        moduleType: "lifesupport",
        level: 4,
        maxHealth: 200,
        width: 1,
        height: 1,
        oxygen: 20,
        consumption: 5,
        price: 4000,
        stock: 1,
        description: "Система жизнеобеспечения по технологиям древних",
    },
    {
        id: "medical-ancient",
        name: "★ Медотсек",
        type: "module",
        moduleType: "medical",
        level: 4,
        maxHealth: 200,
        width: 1,
        height: 1,
        consumption: 5,
        price: 4000,
        stock: 1,
        healing: 15,
        description: "Медицинские технологии древней цивилизации",
    },
    {
        id: "weaponbay-ancient",
        name: "★ Оружейная палуба",
        type: "module",
        moduleType: "weaponbay",
        level: 4,
        maxHealth: 200,
        width: 2,
        height: 2,
        consumption: 5,
        price: 5000,
        stock: 1,
        description: "Платформа для оружия древних",
    },
    {
        id: "ai-core",
        name: "★ ИИ Ядро",
        type: "module",
        moduleType: "ai_core",
        level: 4,
        maxHealth: 200,
        width: 2,
        height: 2,
        consumption: 20,
        price: 8000,
        stock: 1,
        description: "Искусственный интеллект корабля",
    },
    // Boss drops - уникальные модули с особыми эффектами
    {
        id: "ancient-core",
        name: "★ Древнее Ядро",
        type: "module",
        moduleType: "reactor",
        level: 4,
        maxHealth: 200,
        width: 1,
        height: 1,
        power: 25,
        consumption: 0,
        price: 6000,
        stock: 1,
        description: "Ядро древних с повышенной эффективностью",
    },
    {
        id: "conversion-core",
        name: "★ Ядро Конвертации",
        type: "module",
        moduleType: "reactor",
        level: 4,
        maxHealth: 200,
        width: 2,
        height: 1,
        power: 40,
        consumption: 0,
        price: 9000,
        stock: 1,
        description: "Преобразует урон в энергию",
    },
    {
        id: "quantum-engine",
        name: "★ Квантовый Двигатель",
        type: "module",
        moduleType: "engine",
        level: 4,
        maxHealth: 200,
        width: 2,
        height: 2,
        consumption: 0,
        fuelEfficiency: 6,
        price: 12000,
        stock: 1,
        description: "Двигатель на квантовой тяге",
    },
];
