import type { CrewTraitType, MutationTraitId, TraitDetails } from "../types";

export const MUTATION_TRAITS: MutationTraitId[] = [
    "tentacles",
    "third_eye",
    "chitin",
    "telepathy",
    "regeneration",
    "nightmares",
    "paranoid",
    "unstable",
];

export const CREW_TRAITS: Record<
    Exclude<CrewTraitType, "neutral">,
    TraitDetails[]
> = {
    positive: [
        // Common positive traits (60% chance)
        {
            id: "sharpshooter",
            name: "Меткий стрелок",
            desc: "+5% к точности (стрелок в орудийном отсеке)",
            effect: { accuracyBonus: 0.05 },
            rarity: "common",
            priceMod: 1.1,
        },
        {
            id: "experienced",
            name: "Опытный",
            desc: "+15% эффективность",
            effect: { taskBonus: 0.15 },
            rarity: "common",
            priceMod: 1.15,
        },
        {
            id: "charismatic",
            name: "Харизматичный",
            desc: "+10 настроение команды в модуле",
            effect: { moduleMorale: 10 },
            rarity: "common",
            priceMod: 1.1,
        },
        {
            id: "resilient",
            name: "Выносливый",
            desc: "+20% здоровье",
            effect: { healthBonus: 0.2 },
            rarity: "common",
            priceMod: 1.15,
        },
        {
            id: "hardworking",
            name: "Трудолюбивый",
            desc: "+10% к опыту",
            effect: { expBonus: 0.1 },
            rarity: "common",
            priceMod: 1.1,
        },

        // Rare positive traits (30% chance)
        {
            id: "trader",
            name: "Торговец",
            desc: "+10% к цене продажи товаров",
            effect: { sellPriceBonus: 0.1 },
            rarity: "rare",
            priceMod: 1.3,
        },
        {
            id: "veteran",
            name: "Ветеран",
            desc: "+10% точности (стрелок в орудийном отсеке), -40% урона по экипажу",
            effect: { accuracyBonus: 0.1, combatDamageReduction: 0.4 },
            rarity: "rare",
            priceMod: 1.4,
        },
        {
            id: "genius",
            name: "Гений",
            desc: "+30% эффективность, +20% опыт",
            effect: { taskBonus: 0.3, expBonus: 0.2 },
            rarity: "rare",
            priceMod: 1.5,
        },
        {
            id: "leader",
            name: "Лидер",
            desc: "+20 настроение команды, +10% эффективность",
            effect: { moduleMorale: 20, taskBonus: 0.1 },
            rarity: "rare",
            priceMod: 1.4,
        },
        {
            id: "lucky",
            name: "Удачливый",
            desc: "+5% к кредитам за победу в бою",
            effect: { lootBonus: 0.05 },
            rarity: "rare",
            priceMod: 1.45,
        },
        {
            id: "invincible",
            name: "Непобедимый",
            desc: "+40% здоровье, +10% регенерация",
            effect: { healthBonus: 0.4, regenBonus: 0.1 },
            rarity: "rare",
            priceMod: 1.5,
        },
        // Legendary positive traits (10% chance)
        {
            id: "legend",
            name: "Легенда",
            desc: "+50% к макс. здоровью и морали",
            effect: { healthBonus: 0.5, maxHappinessBonus: 0.5 },
            rarity: "legendary",
            priceMod: 2.5,
        },
        {
            id: "master",
            name: "Мастер",
            desc: "Двойной эффект от заданий",
            effect: { doubleTaskEffect: 1 },
            rarity: "legendary",
            priceMod: 2.8,
        },
    ],
    negative: [
        // Common negative traits (50% chance)
        {
            id: "coward",
            name: "Трус",
            desc: "-10 морали в бою каждый ход",
            effect: { combatMoraleDrain: 10 },
            rarity: "common",
            priceMod: 0.9,
        },
        {
            id: "slob",
            name: "Неряха",
            desc: "-5 настроение других",
            effect: { teamMorale: -5 },
            rarity: "common",
            priceMod: 0.9,
        },
        {
            id: "sickly",
            name: "Болезненный",
            desc: "-15% здоровье",
            effect: { healthPenalty: 0.15 },
            rarity: "common",
            priceMod: 0.85,
        },
        // Rare negative traits (30% chance)
        {
            id: "greedy",
            name: "Жадный",
            desc: "-1₢ к цене продажи за каждого жадного в экипаже",
            effect: { sellPricePenalty: 1 },
            rarity: "rare",
            priceMod: 0.7,
        },
        {
            id: "bad_shot",
            name: "Плохой стрелок",
            desc: "-10% точности (стрелок в орудийном отсеке)",
            effect: { accuracyPenalty: 0.1 },
            rarity: "rare",
            priceMod: 0.65,
        },
        {
            id: "pessimist",
            name: "Пессимист",
            desc: "Теряет -30 морали в начале боя",
            effect: { combatStartMoraleDrain: 30 },
            rarity: "rare",
            priceMod: 0.65,
        },
        {
            id: "fragile",
            name: "Хрупкий",
            desc: "-30% здоровье",
            effect: { healthPenalty: 0.3 },
            rarity: "rare",
            priceMod: 0.6,
        },
        {
            id: "rebel",
            name: "Бунтарь",
            desc: "-5 морали себе каждый ход, 5% шанс сбежать в начале боя",
            effect: { moralePenalty: 5, desertionRisk: 0.05 },
            rarity: "rare",
            priceMod: 0.55,
        },
    ],
    // Mutation traits - from Ancient Biosphere curse
    mutation: [
        // Все мутации дают -5 морали экипажу в том же модуле (teamMorale: -5)
        {
            id: "tentacles",
            name: "Мутация: Щупальца",
            desc: "+20% эффективность, -5 морали экипажу в модуле",
            effect: { taskBonus: 0.2, teamMorale: -5 },
            rarity: "mutation",
            priceMod: 1.0,
        },
        {
            id: "third_eye",
            name: "Мутация: Третий глаз",
            desc: "+15% шанс крита (стрелок в оружейном отсеке), -15% макс. здоровья, -5 морали экипажу в модуле",
            effect: { critBonus: 0.15, healthPenalty: 0.15, teamMorale: -5 },
            rarity: "mutation",
            priceMod: 1.0,
        },
        {
            id: "chitin",
            name: "Мутация: Хитин",
            desc: "-25% урона по экипажу в бою, -20% эффективность, -5 морали экипажу в модуле",
            effect: {
                combatDamageReduction: 0.25,
                taskPenalty: 0.2,
                teamMorale: -5,
            },
            rarity: "mutation",
            priceMod: 1.0,
        },
        {
            id: "telepathy",
            name: "Мутация: Телепатия",
            desc: "-5 морали экипажу в модуле, -1 морали всему экипажу корабля, видит врагов и боссов на карте без сканера",
            effect: { teamMorale: -5, shipMorale: -1, seeHostility: 1 },
            rarity: "mutation",
            priceMod: 1.0,
        },
        {
            id: "regeneration",
            name: "Мутация: Регенерация",
            desc: "+5 здоровья/ход, -25% макс. здоровья, -5 морали экипажу в модуле",
            effect: { flatRegen: 5, healthPenalty: 0.25, teamMorale: -5 },
            rarity: "mutation",
            priceMod: 1.0,
        },
        {
            id: "nightmares",
            name: "Мутация: Кошмары",
            desc: "-10 морали себе каждый ход, -5 морали экипажу в модуле",
            effect: { moralePenalty: 10, teamMorale: -5 },
            rarity: "mutation",
            priceMod: 0.7,
        },
        {
            id: "paranoid",
            name: "Мутация: Паранойя",
            desc: "-15 морали себе каждый ход, +10% уклонение (пилот в кабине), -5 морали экипажу в модуле",
            effect: {
                moralePenalty: 15,
                pilotEvasionBonus: 0.1,
                teamMorale: -5,
            },
            rarity: "mutation",
            priceMod: 0.7,
        },
        {
            id: "unstable",
            name: "Мутация: Нестабильность",
            desc: "Случайные перепады настроения (-20..+10), -5 морали экипажу в модуле",
            effect: { moralePenalty: [20, 10], teamMorale: -5 },
            rarity: "mutation",
            priceMod: 0.8,
        },
    ],
};
