// Initial crew - pilot in cockpit (id: 2), others in lifesupport (id: 3)
import type { CrewMember } from "../types";

export const initialCrew: CrewMember[] = [
    {
        id: 1,
        name: "Иванов",
        race: "human",
        profession: "pilot",
        level: 1,
        exp: 0,
        health: 105,
        maxHealth: 105,
        happiness: 80,
        maxHappiness: 100,
        assignment: null,
        assignmentEffect: null,
        combatAssignment: null,
        combatAssignmentEffect: null,
        traits: [],
        moduleId: 2,
        movedThisTurn: false,
        turnsAtZeroHappiness: 0,
    },
    {
        id: 2,
        name: "Петрова",
        race: "human",
        profession: "engineer",
        level: 1,
        exp: 0,
        health: 105,
        maxHealth: 105,
        happiness: 75,
        maxHappiness: 100,
        assignment: null,
        assignmentEffect: null,
        combatAssignment: null,
        combatAssignmentEffect: null,
        traits: [],
        moduleId: 3,
        movedThisTurn: false,
        turnsAtZeroHappiness: 0,
    },
    {
        id: 3,
        name: "Сидоров",
        race: "human",
        profession: "medic",
        level: 1,
        exp: 0,
        health: 105,
        maxHealth: 105,
        happiness: 70,
        maxHappiness: 100,
        assignment: null,
        assignmentEffect: null,
        combatAssignment: null,
        combatAssignmentEffect: null,
        traits: [],
        moduleId: 3,
        movedThisTurn: false,
        turnsAtZeroHappiness: 0,
    },
];
