const base = {
  wave_type: 2,
  p_env_attack: 0.005,
  p_env_sustain: 0.08,
  p_env_punch: 0,
  p_env_decay: 0.16,
  p_base_freq: 0.35,
  p_freq_limit: 0,
  p_freq_ramp: 0,
  p_freq_dramp: 0,
  p_vib_strength: 0,
  p_vib_speed: 0,
  p_arp_mod: 0,
  p_arp_speed: 0,
  p_duty: 0,
  p_duty_ramp: 0,
  p_repeat_speed: 0,
  p_pha_offset: 0,
  p_pha_ramp: 0,
  p_lpf_freq: 1,
  p_lpf_ramp: 0,
  p_lpf_resonance: 0,
  p_hpf_freq: 0,
  p_hpf_ramp: 0,
  sound_vol: 0.28,
  sample_rate: 44_100,
  sample_size: 16,
};

const preset = (overrides) => ({ ...base, ...overrides });
const variants = (overrides, frequencies) => frequencies.map((p_base_freq) => preset({ ...overrides, p_base_freq }));

/** Explicit, non-random jsfxr definitions. wave_type: square=0, saw=1, sine=2, noise=3. */
export const SFX_PRESETS = {
  combat_kinetic: { directory: "combat", presets: variants({ wave_type: 3, p_env_sustain: 0.05, p_env_decay: 0.16, p_freq_ramp: -0.32, p_hpf_freq: 0.28, sound_vol: 0.24 }, [0.23, 0.27, 0.31]) },
  combat_laser: {
    directory: "combat",
    presets: variants(
      { wave_type: 0, p_env_attack: 0.01, p_env_sustain: 0.09, p_env_decay: 0.22, p_freq_ramp: -0.14, p_lpf_freq: 0.36, p_pha_offset: -0.08, sound_vol: 0.24 },
      [0.22, 0.26, 0.3],
    ),
  },
  combat_missile: { directory: "combat", presets: [preset({ wave_type: 3, p_env_attack: 0.02, p_env_sustain: 0.2, p_env_decay: 0.34, p_base_freq: 0.14, p_freq_ramp: -0.08, p_lpf_freq: 0.24, sound_vol: 0.28 })] },
  combat_plasma: { directory: "combat", presets: [preset({ wave_type: 1, p_env_attack: 0.02, p_env_sustain: 0.14, p_env_decay: 0.24, p_base_freq: 0.32, p_freq_ramp: -0.05, p_vib_strength: 0.16, p_vib_speed: 0.58, p_lpf_freq: 0.42, p_pha_offset: 0.16, sound_vol: 0.2 })] },
  combat_drones: { directory: "combat", presets: [preset({ wave_type: 0, p_env_sustain: 0.06, p_env_decay: 0.17, p_base_freq: 0.34, p_repeat_speed: 0.42, p_duty: 0.22, p_freq_ramp: -0.08, sound_vol: 0.16 })] },
  combat_antimatter: { directory: "combat", presets: [preset({ wave_type: 2, p_env_attack: 0.03, p_env_sustain: 0.2, p_env_decay: 0.3, p_base_freq: 0.18, p_freq_ramp: 0.22, p_vib_strength: 0.32, p_vib_speed: 0.76, p_pha_offset: 0.36, sound_vol: 0.22 })] },
  combat_quantum_torpedo: { directory: "combat", presets: [preset({ wave_type: 2, p_env_attack: 0.04, p_env_sustain: 0.2, p_env_decay: 0.34, p_base_freq: 0.14, p_freq_ramp: 0.08, p_vib_strength: 0.12, p_vib_speed: 0.3, p_lpf_freq: 0.22, p_lpf_ramp: 0.15, p_pha_offset: -0.42, sound_vol: 0.26 })] },
  combat_ion_cannon: { directory: "combat", presets: [preset({ wave_type: 0, p_env_attack: 0.005, p_env_sustain: 0.06, p_env_decay: 0.18, p_base_freq: 0.16, p_freq_ramp: -0.16, p_duty: 0.2, p_lpf_freq: 0.18, p_pha_offset: -0.1, sound_vol: 0.25 })] },
  combat_enemy_fire: { directory: "combat", presets: variants({ wave_type: 3, p_env_sustain: 0.05, p_env_decay: 0.16, p_freq_ramp: -0.2, p_lpf_freq: 0.32, sound_vol: 0.22 }, [0.18, 0.22, 0.26]) },
  combat_shield_hit: { directory: "combat", presets: [preset({ wave_type: 2, p_env_attack: 0.01, p_env_sustain: 0.12, p_env_decay: 0.2, p_base_freq: 0.42, p_freq_ramp: 0.18, p_vib_strength: 0.06, p_vib_speed: 0.5, sound_vol: 0.19 })] },
  combat_hull_hit: { directory: "combat", presets: [preset({ wave_type: 3, p_env_sustain: 0.04, p_env_decay: 0.19, p_base_freq: 0.16, p_freq_ramp: -0.22, p_hpf_freq: 0.12, sound_vol: 0.24 })] },
  combat_shield_break: { directory: "combat", presets: [preset({ wave_type: 3, p_env_sustain: 0.12, p_env_decay: 0.33, p_base_freq: 0.28, p_freq_ramp: -0.25, p_lpf_freq: 0.28, sound_vol: 0.25 })] },
  combat_miss: { directory: "combat", presets: [preset({ wave_type: 2, p_env_sustain: 0.07, p_env_decay: 0.2, p_base_freq: 0.38, p_freq_ramp: -0.34, p_hpf_freq: 0.2, sound_vol: 0.14 })] },
  combat_critical: { directory: "combat", presets: [preset({ wave_type: 1, p_env_sustain: 0.08, p_env_decay: 0.2, p_base_freq: 0.62, p_freq_ramp: 0.28, p_arp_mod: -0.22, p_arp_speed: 0.58, sound_vol: 0.2 })] },
  combat_target_select: { directory: "combat", presets: [preset({ wave_type: 2, p_env_sustain: 0.075, p_env_decay: 0.21, p_base_freq: 0.55, p_freq_ramp: 0.08, sound_vol: 0.13 })] },
  combat_enemy_destroyed: { directory: "combat", presets: [preset({ wave_type: 3, p_env_sustain: 0.2, p_env_decay: 0.42, p_base_freq: 0.18, p_freq_ramp: -0.2, p_lpf_freq: 0.22, sound_vol: 0.3 })] },
  combat_player_destroyed: { directory: "combat", presets: [preset({ wave_type: 3, p_env_attack: 0.04, p_env_sustain: 0.36, p_env_decay: 0.58, p_base_freq: 0.1, p_freq_ramp: -0.14, p_lpf_freq: 0.15, sound_vol: 0.32 })] },
  combat_no_active_weapons: { directory: "combat", presets: [preset({ wave_type: 0, p_env_sustain: 0.08, p_env_decay: 0.2, p_base_freq: 0.19, p_freq_ramp: -0.12, p_duty: 0.36, sound_vol: 0.14 })] },

  travel_departure: { directory: "world", presets: [preset({ wave_type: 2, p_env_attack: 0.02, p_env_sustain: 0.16, p_env_decay: 0.28, p_base_freq: 0.23, p_freq_ramp: 0.2, p_vib_strength: 0.04, p_vib_speed: 0.5, sound_vol: 0.18 })] },
  travel_arrival: { directory: "world", presets: [preset({ wave_type: 2, p_env_attack: 0.04, p_env_sustain: 0.18, p_env_decay: 0.26, p_base_freq: 0.28, p_freq_ramp: 0.08, p_arp_mod: -0.12, p_arp_speed: 0.55, sound_vol: 0.17 })] },
  world_danger: { directory: "world", presets: [preset({ wave_type: 0, p_env_sustain: 0.1, p_env_decay: 0.25, p_base_freq: 0.2, p_repeat_speed: 0.48, p_duty: 0.2, sound_vol: 0.2 })] },
  world_discovery: { directory: "world", presets: [preset({ wave_type: 2, p_env_attack: 0.03, p_env_sustain: 0.13, p_env_decay: 0.28, p_base_freq: 0.38, p_freq_ramp: 0.14, p_vib_strength: 0.06, p_vib_speed: 0.36, sound_vol: 0.17 })] },
  world_mining: { directory: "world", presets: [preset({ wave_type: 3, p_env_sustain: 0.08, p_env_decay: 0.2, p_base_freq: 0.25, p_freq_ramp: -0.12, p_hpf_freq: 0.22, sound_vol: 0.18 })] },
  world_artifact: { directory: "world", presets: [preset({ wave_type: 2, p_env_attack: 0.08, p_env_sustain: 0.26, p_env_decay: 0.42, p_base_freq: 0.35, p_vib_strength: 0.18, p_vib_speed: 0.48, p_arp_mod: -0.18, p_arp_speed: 0.72, sound_vol: 0.18 })] },
  world_repair: { directory: "world", presets: [preset({ wave_type: 0, p_env_sustain: 0.08, p_env_decay: 0.18, p_base_freq: 0.3, p_repeat_speed: 0.38, p_duty: 0.42, sound_vol: 0.16 })] },
  world_heal: { directory: "world", presets: [preset({ wave_type: 2, p_env_attack: 0.05, p_env_sustain: 0.16, p_env_decay: 0.25, p_base_freq: 0.36, p_freq_ramp: 0.16, sound_vol: 0.15 })] },
  world_refuel: { directory: "world", presets: [preset({ wave_type: 2, p_env_sustain: 0.13, p_env_decay: 0.22, p_base_freq: 0.24, p_freq_ramp: 0.25, p_vib_strength: 0.05, p_vib_speed: 0.55, sound_vol: 0.16 })] },
  world_install: { directory: "world", presets: [preset({ wave_type: 0, p_env_sustain: 0.06, p_env_decay: 0.17, p_base_freq: 0.32, p_freq_ramp: 0.12, p_duty: 0.38, sound_vol: 0.16 })] },
  world_scrap: { directory: "world", presets: [preset({ wave_type: 3, p_env_sustain: 0.09, p_env_decay: 0.22, p_base_freq: 0.16, p_freq_ramp: -0.25, sound_vol: 0.2 })] },
  world_upgrade: { directory: "world", presets: [preset({ wave_type: 2, p_env_sustain: 0.12, p_env_decay: 0.24, p_base_freq: 0.31, p_freq_ramp: 0.2, p_arp_mod: -0.1, p_arp_speed: 0.6, sound_vol: 0.17 })] },
  world_research: { directory: "world", presets: [preset({ wave_type: 2, p_env_attack: 0.03, p_env_sustain: 0.22, p_env_decay: 0.3, p_base_freq: 0.3, p_vib_strength: 0.08, p_vib_speed: 0.42, p_lpf_freq: 0.58, sound_vol: 0.16 })] },
  world_contract: { directory: "world", presets: [preset({ wave_type: 2, p_env_sustain: 0.11, p_env_decay: 0.22, p_base_freq: 0.42, p_freq_ramp: 0.12, p_arp_mod: -0.1, p_arp_speed: 0.62, sound_vol: 0.15 })] },
  world_crew_milestone: { directory: "world", presets: [preset({ wave_type: 2, p_env_attack: 0.04, p_env_sustain: 0.17, p_env_decay: 0.3, p_base_freq: 0.44, p_freq_ramp: 0.18, p_arp_mod: -0.16, p_arp_speed: 0.58, sound_vol: 0.17 })] },

  ui_dialog_open: { directory: "ui", presets: [preset({ wave_type: 2, p_env_sustain: 0.08, p_env_decay: 0.2, p_base_freq: 0.4, p_freq_ramp: 0.12, sound_vol: 0.1 })] },
  ui_dialog_close: { directory: "ui", presets: [preset({ wave_type: 2, p_env_sustain: 0.07, p_env_decay: 0.19, p_base_freq: 0.4, p_freq_ramp: -0.14, sound_vol: 0.12 })] },
  ui_tab: { directory: "ui", presets: [preset({ wave_type: 2, p_env_sustain: 0.08, p_env_decay: 0.2, p_base_freq: 0.5, p_freq_ramp: 0.04, sound_vol: 0.18 })] },
  ui_confirm: { directory: "ui", presets: variants({ wave_type: 2, p_env_sustain: 0.08, p_env_decay: 0.2, p_freq_ramp: 0.1, sound_vol: 0.11 }, [0.45, 0.51, 0.57]) },
  ui_cancel: { directory: "ui", presets: variants({ wave_type: 2, p_env_sustain: 0.07, p_env_decay: 0.2, p_freq_ramp: -0.12, sound_vol: 0.12 }, [0.31, 0.35, 0.39]) },
  ui_purchase: { directory: "ui", presets: [preset({ wave_type: 2, p_env_sustain: 0.09, p_env_decay: 0.21, p_base_freq: 0.52, p_freq_ramp: 0.18, sound_vol: 0.1 })] },
  ui_error: { directory: "ui", presets: variants({ wave_type: 2, p_env_sustain: 0.08, p_env_decay: 0.21, p_freq_ramp: -0.16, sound_vol: 0.1 }, [0.2, 0.24, 0.28]) },
  ui_notification: { directory: "ui", presets: [preset({ wave_type: 2, p_env_sustain: 0.09, p_env_decay: 0.21, p_base_freq: 0.47, p_freq_ramp: 0.07, sound_vol: 0.12 })] },
};
